apiVersion: v1
kind: Secret
metadata:
  name: {{ include "bizflycloud-certmanager-dns-webhook.fullname" . }}
  labels:
    app: {{ include "bizflycloud-certmanager-dns-webhook.name" . }}
    chart: {{ include "bizflycloud-certmanager-dns-webhook.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: "Opaque"
data:
  groupName: {{ .Values.groupName | quote }}
  authMethod: {{ .Values.authMethod | quote }}
  bizflyEmail: {{ .Values.bizflyEmail }}
  bizflyPassword: {{ .Values.bizflypassword }}
  bizflyRegion: {{ .Values.bizflyRegion }}
  apiURL: {{ .Values.apiURL }}
  tenantID: {{ .Values.tenantID }}
  appCredentialID: {{ .Values.appCredentialID }}
  appCredentialSecret: {{ .Values.appCredentialSecret }}
