apiVersion: v1
kind: Secret
metadata:
  name: {{ include "bizflycloud-certmanager-dns-webhook.fullname" . }}
  labels:
    app: {{ include "bizflycloud-certmanager-dns-webhook.name" . }}
    chart: {{ include "bizflycloud-certmanager-dns-webhook.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: "Opaque"
stringData:
  groupName: {{ .Values.groupName | quote }}
  authMethod: {{ .Values.authMethod | quote }}
  bizflyEmail: {{ .Values.bizflyEmail }}
  {{- if eq .Values.authMethod "password"}}
  bizflyPassword: {{ .Values.bizflyPassword }}
  {{- else if eq .Values.authMethod "application_credential"}}
  appCredentialID: {{ .Values.appCredentialID }}
  appCredentialSecret: {{ .Values.appCredentialSecret }}
  {{end }}